import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

// Components
import Navbar from "./components/Navbar";

const inter = Inter({ 
  subsets: ["latin"]
 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <head>
        <title>HomeTribe</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head> 
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
